### ISSUE TITLE
单个用户爬取不会受限制吗？

### ISSUE THREAD

**Issue by misstt123** [zhenye163/spider-zhihu#1]

**Comment by zhenye163** [comment]
知乎有反爬机制的，

**Comment by zhenye163** [comment]
知乎是一个靠内容营销的论坛。

**Comment by zhenye163** [comment]
知乎是一个靠内容营销的论坛。不登录也是可以访问其部分内容的。
但是知乎是有反爬机制的。同一个IP高频访问，知乎是会将这个IP加入黑名单的。
我测试的时候，爬取7-8万数据，IP被屏蔽了。
所以才会采用切换代理的方式爬取数据。
