### ISSUE TITLE
DB迁移数据到es没有写接口呢，大佬

### ISSUE THREAD

**Issue by tingyunote** [zhenye163/spider-zhihu#2]
ZhihuUserRepository DB迁移数据到es没有写接口呢，大佬

**Comment by zhenye163** [comment]
UserController里面transferDataFromDBToES()方法就是项目向外暴露的数据迁移接口。
启动项目，配置好ES环境，在postman和浏览器中输入该接口的GET请求路径---localhost:8980/users/transfer，就可以迁移数据了。
