### ISSUE TITLE
能否提供数据库的脚本文件呢

### ISSUE THREAD

**Issue by tingyunote** [zhenye163/spider-zhihu#3]
能否提供数据库的脚本文件呢包括数据和数据结构

**Comment by zhenye163** [comment]
项目选用的ORM框架是JPA，不需要手动创建表。
只要你创建一个数据库。
修改项目配置文件application-dev.properties里面该数据的url,username,password。
本地启动SpringBoot项目，JPA规范会自动创建数据库表的。

要保证项目能够成功启动，还需要先在本地配置好redis和rabbitmq环境，这个配置不用改，默认就行。还要配置好ES环境，ES配置里面的两个参数，跟ES配置文件里面的一致就行。

**Comment by zhenye163** [comment]
readme.md文件里面记录了如何在本地启动这个项目，也记录了如何在云服务器上启动发布这个项目。
这都是我实际操作的记录，只要用的版本一致，应该是能够重现的。

**Comment by tingyunote** [comment]
![image](https://user-images.githubusercontent.com/26685651/81367795-b9c68e80-9120-11ea-9913-3832bc09ba8e.png)
不知道这个是什么原因呢

**Comment by zhenye163** [comment]
我刚刚测试过，代码没有做任何改动，是能够正常启动项目的。


应该是要修改配置文件内容---seimi.crawler.enabled=true。
配置文件中【seimi.crawler.enabled】这个配置没有开启。是无法使用这个框架爬取爬虫的。










在 2020-05-08 11:40:58，"RansongZ" <notifications@github.com> 写道：


不知道这个是什么原因呢
